services:
  spring:
    image: ${IMAGE_URL}/ktb-01:${IMAGE_TAG}
    ports:
      - "8080:8080"
    container_name: spring-container
    env_file:
      - .env.spring
    networks:
      - ktb
    restart: always

networks:
  ktb:
    name: ktb
    driver: bridge
    external: true